  - name: Create nodes
    bigip_node:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      host: "{{item.host}}"
      name: "{{item.host}}"
      validate_certs: False
    with_items: "{{pool_members}}"
    delegate_to: localhost

  - name: Create pool
    bigip_pool:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      name: "{{pool_name}}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      validate_certs: False
    delegate_to: localhost

  - name: Add Pool members
    bigip_pool_member:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      name: "{{item.host}}"
      host: "{{item.host}}"
      port: "{{item.port}}"
      pool: "{{pool_name}}"
      validate_certs: False
    with_items: "{{pool_members}}"
    delegate_to: localhost

  - name: Add Virtual Server
    bigip_virtual_server:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      name: "{{ app_name }}_vs_https"
      destination: "{{ vip_ip }}"
      port: "{{ vip_port }}"
      all_profiles:
       - http
       - name: clientssl
         context: client-side
      pool: "{{pool_name}}"
      snat: "automap"
      irules:
      - "_sys_https_redirect"
      validate_certs: False
    delegate_to: localhost

  - name: Add Redirect Virtual Server
    bigip_virtual_server:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      name: "{{ app_name }}_vs_http_redirect"
      destination: "{{ vip_ip }}"
      port: "80"
      all_profiles:
       - http
      irules:
      - "_sys_https_redirect"
      validate_certs: False
    delegate_to: localhost

